export const GET_FAVORITES = 'GET_FAVORITES'
export const SET_FAVORITES_LIST = 'SET_FAVORITES_LIST'
export const CREATE_FAVORITE = 'CREATE_FAVORITE'
export const ADD_OBJECTS_TO_FAVORITE = 'ADD_OBJECTS_TO_FAVORITE'